//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerkkokauppaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int LoginID { get; set; }
        public int AsiakasID { get; set; }
        public string Email { get; set; }
        public string Salasana { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
    }
}
